#!/usr/bin/env bash
set -e

# Only run on pushes to master
while read local_ref local_oid remote_ref remote_oid; do
  if [ "$remote_ref" = "refs/heads/master" ]; then
    cd src

    echo "=== Linting ==="
    bunx oxlint@latest ./ --ignore-pattern=*.test.* --fix

    echo "=== Testing ==="
    bun test

    echo "=== Deploying global commands ==="
    bun deploy_global_cmds.ts
  fi
done
